services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_USER: ek
      MYSQL_PASSWORD: ek
      MYSQL_ROOT_PASSWORD: ek
    ports:
      - "127.0.0.1:3306:3306"